### ISSUE TITLE
Payment Gateway

### ISSUE THREAD

**Issue by obutuz** [shavit/Miley#1]
Dear Shavit

I would like to add a new payment gateway, do you mind directing me to the right files that I should edit?

**Comment by shavit** [comment]
Yes, It is using `PayPalPaymentsForm` https://github.com/shavit/Miley/blob/master/payments/views.py#L9

**Comment by obutuz** [comment]
Thanks Buddy. I have a few more questions, kindly if you don't mind send me a blank email to aobutu(at)futurevh.com. I would like to pick your mind on a few items
